services:
  - postgresql
  - redis-server

env:
  global:
  - RCTF_DATABASE_URL=postgres://postgres@localhost/rctf
  - RCTF_REDIS_URL=redis://@localhost:6379/0

language: node_js
node_js:
  - 12
before_script:
  - psql -c 'create database rctf;' -U postgres
script:
  - cp .env.example .env
  - cp -r .rdeploy.example .rdeploy
  - yarn migrate up
  - yarn lint
  - yarn test