branches:
  only:
    - "master"

services:
  - postgresql
  - redis-server

env:
  global:
  - RCTF_DATABASE_URL=postgres://postgres@localhost/rctf
  - RCTF_REDIS_URL=redis://@localhost:6379/0

language: node_js
node_js:
  - 12
  - node
before_script:
  - psql -c 'create database rctf;' -U postgres
install:
  - npm install -g codecov
script:
  - cp .env.example .env
  - cp -r .rdeploy.example .rdeploy
  - yarn migrate up
  - yarn build
  - yarn lint
  - yarn test:report
  - codecov
