version: '2.2'
services:
  rctf:
    build: .
    restart: always
    ports:
      - '127.0.0.1:8080:80'
    networks:
      - rctf
    env_file:
      - .env
    environment:
      - PORT=80
      - RCTF_DATABASE_HOST=postgres
      - RCTF_DATABASE_DATABASE=rctf
      - RCTF_DATABASE_USERNAME=rctf
      - RCTF_DATABASE_PASSWORD=${RCTF_DATABASE_PASSWORD}
      - RCTF_REDIS_URL=redis://redis
      - RCTF_DATABASE_MIGRATE=before
    volumes:
      - ./conf.d:/app/dist/conf.d
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:5.0.9
    restart: always
    networks:
      - rctf
    volumes:
      - ./data/rctf-redis:/data
  postgres:
    image: postgres:12.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=${RCTF_DATABASE_PASSWORD}
      - POSTGRES_USER=rctf
      - POSTGRES_DB=rctf
    networks:
      - rctf
    volumes:
      - ./data/rctf-postgres:/var/lib/postgresql/data

networks:
  rctf: {}
