# The logo for this CTF
logoUrl: 'https://example.com'

# CHANGE THIS: Must be a 32 byte base64 encoded secret
# For example, run `head -c32 </dev/random | base64`
tokenKey: 

#corsOrigin: 

# Uncomment below to enable CTF OAuth
#ctftimeClientSecret: 
#ctftimeClientId: 

challengeProvider: 
  name: 'challenges/rdeploy-blob'
  options:
    rDeployDirectory: '.rdeploy'
    rDeployFiles: 'files'
    updateInterval: 60000

uploadProvider:
  name: 'uploads/local'
  options:
    uploadDirectory: 'uploads'
    endpoint: '/uploads'

# uncomment these lines to enable email auth
# emailProvider:
#   name: 'emails/smtp'
#   options:
#     smtpUrl: smtps://a:b@example.com
# emailProvider:
#   name: 'emails/ses'
#   options:
#     awsKeyId: AAAAAA
#     awsKeySecret: abcd
#     awsRegion: aa-bbbb-1
# emailFrom: no-reply@example.com

# uncomment these lines for division ACLs
# divisionACLs:
#   - match: any
#     divisions:
#       - hs
#       - college
#       - other
defaultDivision: other

leaderboard:
  maxLimit: 100
  maxOffset: 4294967296 # 2**32
  updateInterval: 10000
  graphMaxTeams: 10
  graphSampleTime: 1800000

removeDownloadHashes: true
loginTimeout: 3600000
