site_name: rCTF
site_description: rCTF Documentation
site_author: redpwn
site_url: https://rctf.redpwn.net
dev_addr: 0.0.0.0:8000

repo_name: GitHub
repo_url: https://github.com/redpwn/rctf
edit_uri: blob/master/docs/content/

docs_dir: content

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: blue
    accent: blue

extra_javascript:
  - https://cdn.jsdelivr.net/npm/zepto@1.2.0/dist/zepto.min.js

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: '#'
