site_name: rCTF
site_description: rCTF Documentation
site_author: redpwn
site_url: https://rctf.redpwn.net

repo_name: GitHub
repo_url: https://github.com/redpwn/rctf
edit_uri: blob/master/docs/content/

docs_dir: content

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: blue
    accent: blue

extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
extra_css:
  - assets/styles/rtd-override.css

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: '#'
